version: '25.0'

services:

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#
#    ports:
#      - "3000:3000"
#    restart: always
#
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: backend
#    ports:
#      - "8080:8080"
#    restart: always
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=anon123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
#    depends_on:
#      - db

  db:
    image: postgres
    container_name: postgresDB
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: anon123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
